import { NextRequest } from 'next/server'
import { generateObject } from 'ai'
import { openai } from '@ai-sdk/openai'
import { z } from 'zod'
import { eq } from 'drizzle-orm'
import { db } from '@/db'
import { flows, steps, stepOptions } from '@/db/schema'
import { FlowGenerationSchema } from '@/lib/schemas/flow-generation'
import { FLOW_GENERATOR_SYSTEM, buildFlowGeneratorPrompt } from '@/lib/prompts/generate-flow'
import { withApiHandler } from '@/lib/with-api-handler'
import { apiCreated } from '@/lib/api-response'
import { ValidationError, InternalError } from '@/lib/errors'
import { createLogger } from '@/lib/logger'

const log = createLogger('flows/generate')

// Vercel Pro: allow up to 60s for LLM generation
export const maxDuration = 60

const RequestSchema = z.object({
  prompt: z.string().min(10, 'El prompt debe tener al menos 10 caracteres').max(500),
  scoringGoal: z.string().min(5, 'Describe qué quieres evaluar').max(300),
})

export const POST = withApiHandler(async (req: NextRequest, { auth }) => {
  const { org, userId } = auth

  // Validate input
  const body = await req.json()
  const parsed = RequestSchema.safeParse(body)
  if (!parsed.success) {
    throw new ValidationError('Prompt inválido', parsed.error.flatten().fieldErrors)
  }
  const { prompt, scoringGoal } = parsed.data

  log.info({ userId, orgId: org.id, promptLength: prompt.length }, 'Generating flow')

  // Generate flow with AI
  const { object: generated } = await generateObject({
    model: openai('gpt-4o-mini'),
    schema: FlowGenerationSchema,
    system: FLOW_GENERATOR_SYSTEM,
    prompt: buildFlowGeneratorPrompt(prompt, scoringGoal),
  })

  log.info(
    { orgId: org.id, flowName: generated.flow.name, stepCount: generated.steps.length },
    'Flow generated by AI, saving to DB'
  )

  // Persist without db.transaction — neon-http does not support transactions.
  // On partial failure we delete the flow (CASCADE cleans steps/options).
  let newFlow: (typeof flows.$inferSelect) | undefined
  try {
    const [inserted] = await db
      .insert(flows)
      .values({
        organizationId: org.id,
        name: generated.flow.name,
        description: generated.flow.description,
        promptOrigin: prompt,
        status: 'draft',
        settings: generated.flow.settings,
        scoringCriteria: {
          ...generated.flow.scoring_criteria,
          objective: scoringGoal,
        },
      })
      .returning()

    if (!inserted) throw new Error('insert flows returned no row')
    newFlow = inserted

    for (const step of generated.steps) {
      const [newStep] = await db
        .insert(steps)
        .values({
          flowId: newFlow.id,
          order: step.order,
          type: step.type,
          question: step.question,
          hint: step.hint ?? null,
          placeholder: step.placeholder ?? null,
          variableName: step.variable_name,
          required: step.required,
          conditions: step.conditions ?? null,
          fileConfig: step.file_config ?? null,
        })
        .returning()

      if (!newStep) throw new Error('insert steps returned no row')

      if (step.options && step.options.length > 0) {
        await db.insert(stepOptions).values(
          step.options.map((opt) => ({
            stepId: newStep.id,
            label: opt.label,
            value: opt.value,
            emoji: opt.emoji ?? null,
            order: opt.order,
          })),
        )
      }
    }
  } catch (err) {
    log.error({ err, orgId: org.id, flowId: newFlow?.id }, 'DB insert failed during flow creation')
    if (newFlow) {
      await db.delete(flows).where(eq(flows.id, newFlow.id))
    }
    throw new InternalError('Error guardando el flow en la base de datos')
  }

  const result = newFlow

  log.info({ flowId: result.id, orgId: org.id }, 'Flow created successfully')

  return apiCreated({ flow: result })
}, { requireAuth: true })
