import { NextRequest } from 'next/server'
import { generateObject } from 'ai'
import { z } from 'zod'
import { eq } from 'drizzle-orm'
import { db } from '@/db'
import { flows, steps, stepOptions } from '@/db/schema'
import { FlowGenerationSchema } from '@/lib/schemas/flow-generation'
import { FLOW_GENERATOR_SYSTEM, buildFlowGeneratorPrompt, type FlowGeneratorExtras } from '@/lib/prompts/generate-flow'
import { withApiHandler } from '@/lib/with-api-handler'
import { apiCreated } from '@/lib/api-response'
import { ValidationError, InternalError } from '@/lib/errors'
import { createLogger } from '@/lib/logger'
import {
  FLOW_GENERATE_PROMPT_MAX_CHARS,
  FLOW_GENERATE_SCORING_GOAL_MAX_CHARS,
} from '@/lib/flow-generate-input-limits'
import {
  assertGenerativeAiConfigured,
  getStructuredModelProviderChain,
  getStructuredOutputModelForProvider,
} from '@/lib/ai-model'

const log = createLogger('flows/generate')

// Vercel Pro: allow up to 60s for LLM generation
export const maxDuration = 60

const RequestSchema = z.object({
  prompt: z
    .string()
    .min(10, 'El prompt debe tener al menos 10 caracteres')
    .max(FLOW_GENERATE_PROMPT_MAX_CHARS, `El prompt no puede superar ${FLOW_GENERATE_PROMPT_MAX_CHARS} caracteres`),
  scoringGoal: z
    .string()
    .min(5, 'Describe qué quieres evaluar')
    .max(
      FLOW_GENERATE_SCORING_GOAL_MAX_CHARS,
      `El objetivo de medición no puede superar ${FLOW_GENERATE_SCORING_GOAL_MAX_CHARS} caracteres`,
    ),
  flowName: z.string().min(2).max(200).optional(),
  description: z.string().min(1).max(2000).optional(),
  toneAssistant: z.string().min(3).max(220).optional(),
  /** Vacío = saludo automático desde la descripción en runtime. */
  chatIntro: z.string().max(4000).optional(),
})

export const POST = withApiHandler(async (req: NextRequest, { auth }) => {
  const { org, userId } = auth

  assertGenerativeAiConfigured()

  // Validate input
  const body = await req.json()
  const parsed = RequestSchema.safeParse(body)
  if (!parsed.success) {
    throw new ValidationError('Prompt inválido', parsed.error.flatten().fieldErrors)
  }
  const { prompt, scoringGoal, flowName, description, toneAssistant, chatIntro } = parsed.data

  log.info({ userId, orgId: org.id, promptLength: prompt.length }, 'Generating flow')

  const extras: FlowGeneratorExtras | undefined =
    flowName?.trim() || description?.trim() || toneAssistant?.trim()
      ? {
          flowName: flowName?.trim(),
          descriptionHint: description?.trim(),
          toneHint: toneAssistant?.trim(),
        }
      : undefined

  // Generate flow with AI (primario según AI_PROVIDER; si falla y hay clave del otro, reintento allí)
  const providerChain = getStructuredModelProviderChain()
  const genPrompt = buildFlowGeneratorPrompt(prompt, scoringGoal, extras)
  let generated: z.infer<typeof FlowGenerationSchema> | undefined
  let lastErr: unknown
  for (let i = 0; i < providerChain.length; i++) {
    const provider = providerChain[i]!
    try {
      const { object } = await generateObject({
        model: getStructuredOutputModelForProvider(provider),
        schema: FlowGenerationSchema,
        system: FLOW_GENERATOR_SYSTEM,
        prompt: genPrompt,
      })
      generated = object
      if (i > 0) {
        log.info(
          { orgId: org.id, provider, flowName: object.flow.name, stepCount: object.steps.length },
          'Flow generated by AI using fallback provider'
        )
      }
      break
    } catch (err) {
      lastErr = err
      const next = providerChain[i + 1]
      if (next) {
        log.warn({ err, orgId: org.id, provider, nextProvider: next }, 'generateObject failed, trying alternate AI provider')
      } else {
        log.error({ err, orgId: org.id, provider }, 'generateObject failed on all configured providers')
      }
    }
  }
  if (!generated) {
    throw lastErr ?? new InternalError('No se pudo generar el flow')
  }

  log.info(
    { orgId: org.id, flowName: generated.flow.name, stepCount: generated.steps.length },
    'Flow generated by AI, saving to DB'
  )

  // Persist without db.transaction — neon-http does not support transactions.
  // On partial failure we delete the flow (CASCADE cleans steps/options).
  let newFlow: (typeof flows.$inferSelect) | undefined
  try {
    const resolvedName = (flowName?.trim() || generated.flow.name).trim().slice(0, 200)
    const resolvedDescription = (description?.trim() || generated.flow.description).trim().slice(0, 2000)
    const resolvedTone = (toneAssistant?.trim() ||
      (typeof generated.flow.settings.tone === 'string' && generated.flow.settings.tone.trim()
        ? generated.flow.settings.tone.trim()
        : 'cálido, breve y natural'))!.slice(0, 220)
    const resolvedChatIntro =
      chatIntro !== undefined
        ? chatIntro.slice(0, 4000)
        : typeof generated.flow.settings.chat_intro === 'string'
          ? generated.flow.settings.chat_intro.slice(0, 2000)
          : ''

    const [inserted] = await db
      .insert(flows)
      .values({
        organizationId: org.id,
        name: resolvedName,
        description: resolvedDescription,
        promptOrigin: prompt,
        status: 'draft',
        settings: {
          ...generated.flow.settings,
          transition_style: generated.flow.settings.transition_style ?? 'ai',
          tone: resolvedTone,
          chat_intro: resolvedChatIntro,
        },
        scoringCriteria: {
          ...generated.flow.scoring_criteria,
          objective: scoringGoal,
        },
      })
      .returning()

    if (!inserted) throw new Error('insert flows returned no row')
    newFlow = inserted

    for (const step of generated.steps) {
      const [newStep] = await db
        .insert(steps)
        .values({
          flowId: newFlow.id,
          order: step.order,
          type: step.type,
          question: step.question,
          hint: step.hint ?? null,
          placeholder: step.placeholder ?? null,
          variableName: step.variable_name,
          required: step.required,
          conditions: step.conditions ?? null,
          fileConfig: step.file_config ?? null,
          branchLabel: step.branch_label ?? null,
          branchColor: step.branch_color ?? null,
        })
        .returning()

      if (!newStep) throw new Error('insert steps returned no row')

      if (step.options && step.options.length > 0) {
        await db.insert(stepOptions).values(
          step.options.map((opt) => ({
            stepId: newStep.id,
            label: opt.label,
            value: opt.value,
            emoji: opt.emoji ?? null,
            order: opt.order,
          })),
        )
      }
    }
  } catch (err) {
    log.error({ err, orgId: org.id, flowId: newFlow?.id }, 'DB insert failed during flow creation')
    if (newFlow) {
      await db.delete(flows).where(eq(flows.id, newFlow.id))
    }
    throw new InternalError('Error guardando el flow en la base de datos')
  }

  const result = newFlow

  log.info({ flowId: result.id, orgId: org.id }, 'Flow created successfully')

  return apiCreated({ flow: result })
}, { requireAuth: true })
